_format_version: "3.0"
_transform: true

services:
  - name: service-template
    url: http://service-template:3000
    routes:
      - name: service-template-health
        paths:
          - /health
      - name: service-template-root
        paths:
          - /service-template
