packages:
  - 'apps/*'
  - 'services/*'
  - 'packages/*'
  - 'infra/*'
  - 'service-template'

allowBuilds:
  esbuild: true
  prisma: true
  "@prisma/client": true
  "@prisma/engines": true
  sharp: true
  unrs-resolver: true
